name: steers-test
channels:
- conda-forge
dependencies:
- python>=3.9
- pip

  # interactive python
- ipython
- jupyterlab

  # publishing
- jupyter-book
- ghp-import

- pydata-sphinx-theme==0.13.1  # 0.13.2 is incompatible with sphinx-book-theme 1.0.0; see raised bug issue here: https://github.com/executablebooks/sphinx-book-theme/issues/711